version: 0.2

env:
    variables:
        BUILD_TYPE: jar
        DOCKER_USERNAME: juliantheking
        DOCKER_PASSWORD: Omega1999
        PROJECT_NAME: demo1

phases: 
    install:
        runtime-versions:
            java: corretto17
            docker: 18
        commands:
            - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
            - timeout 15 sh -c "until docker info; do echo .; sleep 1;
    pre_build:
        commands:
            - echo "Build type is $BUILD_TYPE"
            - echo "Fetching repository token ..."
            - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain factory --domain-owner 781648067507 --region eu-central-1 --query authorizationToken --output text`
            - if [ "$BUILD_TYPE" = "docker" ]; then echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin; fi
    build:
        commands:
            - echo "Resolving dependencies"
            - mvn dependency:resolve
            - echo "Building $BUILD_TYPE ..."
            - if [ "$BUILD_TYPE" = "jar" ]; then mvn -s settings.xml clean package;
              elif [ "$BUILD_TYPE" = "docker" ]; then docker build -t ${DOCKER_USERNAME}/${PROJECT_NAME} .;
              else echo "Unknown build type"; exit 1; fi
    repository:
        commands:
            - echo "Publishing $BUILD_TYPE to repository ..."
            - if [ "$BUILD_TYPE" = "jar" ]; then mvn -s settings.xml deploy;
                elif [ "$BUILD_TYPE" = "docker" ]; then docker push ${DOCKER_USERNAME}/${PROJECT_NAME};
                else echo "Unknown build type"; exit 1; fi
cache:
    paths:
        - '/root/.m2/**/*'
        - '/root/.npm/**/*'
        - '/root/.pip-cache/**/*'
        - '/root/.docker/**'