apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo1-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: demo1-service
                port:
                  number: 4444
            pathType: ImplementationSpecific
            path: /